### ISSUE TITLE
requestLayout() improperly called by ____, issue with Magnus S2/S3 Inventory

### ISSUE THREAD

**Issue by trevorcmit** [cslrfid/CS710S-C-Sharp-APP-for-iOS-ANDROID-UWP#2]
Hi cslrfid,

I'm running into an issue with the Magnus S2/S3 Inventory Special Function on this app when using Android. For reference, using a Google Pixel 7 Pro, Android 13.0 - API 33.

I have uncommented the Magnus S2/S3 Inventory Special Function menu since that is the desired functionality I am using (however this issue seems to apply to multiple of the Inventory screens such as the basic InventorynScan). 

I can get to the Inventory screen fine with no errors, then when I start reading my Output in VS gives me dozens of lines of errors saying:

[View] requestLayout() improperly called by crc64720bb2db43a66fe9.NavigationPageRenderer{4432a29 V.E...... ......I. 0,0-1080,2169 #1} during second layout pass: posting in next frame
[View] requestLayout() improperly called by crc643f46942d9dd1fff9.Platform_DefaultRenderer{171963d V.E...... ......ID 0,0-1080,116} during layout: running second layout pass
[View] requestLayout() improperly called by crc643f46942d9dd1fff9.Platform_DefaultRenderer{ac5e63e V.E...... ......ID 0,0-1080,116} during layout: running second layout pass
[View] requestLayout() improperly called by crc643f46942d9dd1fff9.Platform_DefaultRenderer{37f31ab V.E...... ......ID 0,0-1080,116} during layout: running second layout pass
[View] requestLayout() improperly called by crc643f46942d9dd1fff9.Platform_DefaultRenderer{ba482e4 V.E...... ......ID 0,0-1080,116} during layout: running second layout pass
...

I think something may be occurring with the ObservableCollection TagInfoList? I am trying to display more columns worth of TagInfoList data, the four values EPC, OCRSSI, SensorAvgValue, and SucessCount, yet SucessCount never updates (it is always 0 even when incrementing with ++) and SensorAvgValue never displays, even though I have confirmed it is being fed the correct type of String. Even the unchanged AddUpdateTagData() function has these same errors. I have tried both my own update function and the aforementioned one and neither solves these issues.

Also, I am not sure if it is just an XAML difference (in the file `PageRFMicronS3Inventory.xaml` ) between MvvmCross and the old method you guys used for the CS108 app on the older version of Xamarin Forms. I don't know exactly what the difference between pages:BasePage and the pages:MvxContentPage is but I am looking into it.

I have also tried:
- Not invoking AppUpdateTagData on the main thread
- removing all interface buttons/labels except for Start Inventory button and the ListView
Neither of these have worked.

Any advice?

Trevor

**Comment by ksclam** [comment]
The Magnus S2/S3 sensor tags reading page on the CS710S demo app is still work in progress.  It will be fully integrated in the upcoming releases.
